import Sound from "react-native-sound";

export const animalSounds = {
  Chris: {
    Bear: new Sound(require("./ChrisBear.m4a")),
    Cat: new Sound(require("./ChrisCat.m4a")),
    Chicken: new Sound(require("./ChrisChicken.m4a")),
    Cow: new Sound(require("./ChrisCow.m4a")),
    Dog: new Sound(require("./ChrisDog.m4a")),
    Frog: new Sound(require("./ChrisFrog.m4a")),
    Gorilla: new Sound(require("./ChrisGorilla.m4a")),
    Koala: new Sound(require("./ChrisKoala.m4a")),
    Lion: new Sound(require("./ChrisLion.m4a")),
    Monkey: new Sound(require("./ChrisMonkey.m4a")),
    Owl: new Sound(require("./ChrisOwl.m4a")),
    Panda: new Sound(require("./ChrisPanda.m4a")),
    Penguin: new Sound(require("./ChrisPenguin.m4a")),
    Pig: new Sound(require("./ChrisPig.m4a")),
    Raccoon: new Sound(require("./ChrisRaccoon.m4a")),
    Sheep: new Sound(require("./ChrisSheep.m4a")),
  },
  Hannah: {
    Bear: new Sound(require("./HannahBear.m4a")),
    Cat: new Sound(require("./HannahCat.m4a")),
    Chicken: new Sound(require("./HannahChicken.m4a")),
    Cow: new Sound(require("./HannahCow.m4a")),
    Dog: new Sound(require("./HannahDog.m4a")),
    Frog: new Sound(require("./HannahFrog.m4a")),
    Gorilla: new Sound(require("./HannahGorilla.m4a")),
    Koala: new Sound(require("./HannahKoala.m4a")),
    Lion: new Sound(require("./HannahLion.m4a")),
    Monkey: new Sound(require("./HannahMonkey.m4a")),
    Owl: new Sound(require("./HannahOwl.m4a")),
    Panda: new Sound(require("./HannahPanda.m4a")),
    Penguin: new Sound(require("./HannahPenguin.m4a")),
    Pig: new Sound(require("./HannahPig.m4a")),
    Raccoon: new Sound(require("./HannahRaccoon.m4a")),
    Sheep: new Sound(require("./HannahSheep.m4a")),
  },
};
