# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci
    match(type: "appstore", readonly: true)
    increment_build_number(xcodeproj: "matchimals.xcodeproj")
    build_app(workspace: "matchimals.xcworkspace", scheme: "matchimals")
    pilot(api_key_path: "fastlane/fastlane-api-key.json", skip_waiting_for_build_processing: true)
  end
end
