export const colors = {
  redLight: "#FF9E9C",
  redMedium: "#DB7270",
  orangeMedium: "#CD7547",
  yellowLight: "#FFEA87",
  greenLight: "#CAE1C3",
  greenMedium: "#7A9572",
  blueLight: "#C5E5F0",
  blueMedium: "#7698A4",
  blueDark: "#364F57",
  purpleMedium: "#94638D",
  grayExtraLight: "#EAEAEA",
  grayLight: "#9F9FB7",
  grayMedium: "#5D5D6B",
  grayDark: "#17171b",
};

export const animalColors = {
  Bear: colors.redMedium,
  Cat: colors.redLight,
  Chicken: colors.greenMedium,
  Cow: colors.purpleMedium,
  Dog: colors.blueMedium,
  Frog: colors.blueLight,
  Gorilla: colors.yellowLight,
  Koala: colors.greenLight,
  Lion: colors.yellowLight,
  Monkey: colors.redLight,
  Owl: colors.redMedium,
  Panda: colors.blueLight,
  Penguin: colors.greenLight,
  Pig: colors.blueMedium,
  Raccoon: colors.purpleMedium,
  Sheep: colors.greenMedium,
};
